version: "2.4"
services:
  pupil:
    build: .
    network_mode: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /root/.Xauthority:/root/.Xauthority
      - ${PWD}:/pupil_detect
